baseURL = "https://brandbook-tau.vercel.app/"
languageCode = "ru-ru"
title = "Брендбук"
theme = "github.com/colinwilson/lotusdocs"

[module]
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[params]
  # Включает боковое меню в разделах документации
  docsMenu = true 
  # Позволяет главной странице использовать всю ширину экрана
  containerFluid = true