baseURL = 'baseURL = "https://courageous-capybara-7d23e2.netlify.app/"'
languageCode = 'ru-ru'
title = 'Брендбук'

# Подключаем ядро Lotus Docs и компилятор стилей Bootstrap
[module]
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

# Включаем автоматическое боковое меню
[params]
  docsMenu = true