backend:
  name: git-gateway
  branch: main # или master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "docs"
    label: "Документация"
    folder: "content/docs"
    extension: "md"
    format: "frontmatter"
    frontmatter_delimiter: "+++" # Важно для твоих файлов
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Текст", name: "body", widget: "markdown"}