backend:
  name: git-gateway
  branch: main # ПРОВЕРЬ ЕЩЕ РАЗ В GITHUB: ТОЧНО main? НЕ master?
display_url: https://courageous-capybara-7d23e2.netlify.app
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: "docs"
    label: "Docs"
    folder: "content/docs"
    extension: "md"
    format: "frontmatter"
    frontmatter_delimiter: "+++" # Чтобы он понимал твои файлы с +++
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}